### ISSUE TITLE
Version 2.0 Progress Tracking

### ISSUE THREAD

**Issue by ihadeed** [zyra/ionic2-super-tabs#14]
Hey everyone,

I'm working on a big update for this module. There has been lots of progress already and I'm sure you will all love the results. This issue is to track the progress, I will update the related issues once I push the commit and release the next version.

# Features
- [x] Allow tabs scrolling
  - [x] Can have many tabs with a tab bar that's expanded and scrolls automatically on tab change
  - [x] Can manually scroll through the available tabs
- [x] Allow swipe-back on iOS _(issue #4)_
- [x] Allow swiping on top of the tab contents to open side menu _(issue #10)_
- [x] Allow disabling/enabling swiping _(issue #2)_
  - [x] Global setting
  - [x] Per tab setting
- [x] Allow programmatic navigation to a specific tab  _(issue #3)_
- [x] Add badges for tabs _(issue #6)_
- [x] Add ability to show/hide tab-bar _(issue #1)_
- [x] Add ability to specify tabs position, or respect the global Ionic config (top/bottom tabs) _(issue #9)_
- [x] Output `tabSelect` event

# Bug fixes
- [X] Empty tab at the end
- [x] Fix issues with part of the tab bar hiding when scrolling to the bottom of the page 
- [x] Fix issues caused when switching screen orientation
- [x] Fix issue where `ion-slides` gets stuck between two slides (tabs). It will navigate to the closest tab when this occurs.
- [x] Fix issue with indicator width not being updated when orientation changes _(issue #11)_

# Other
- [X] Disable overswiping (at the beginning and end of the tabs)
- [X] Improve animation performance
- [X] Create custom code instead of using `ion-slides`

---

## What the upcoming version is like
1. There will be a provider `SuperTabsController` that will be used to:
    - enable/disable swiping for all tabs or when a specific tab is selected
    - increase/decrease/clear badge for a specific tab
    - enable/disable a tab (might not be included in initial v2 release)
2. The main Module will have a static `forRoot` method.
3. Each tab will accept an `id` attribute so you can use it in any of the `SuperTabsController` methods.

---

### Removed inputs
- `rootNavCtrl`: the root NavController is now automatically added to the NavParams

### Renamed Inputs
- **SuperTabs** component:
    - `sliderColor` -> `indicatorColor`
    - `toolbarColor` -> `toolbarBackground`
    - `tabsColor` -> `toolbarColor`

- **SuperTab** component:
    - `tabRoot` -> `root`
    - `navParams` -> `rootParams`

### Other
- `SuperTabs` component `height` input no longer takes a `string`. It takes a number of pixels instead. You most likely will not need to use this input since the height now defaults to `100%`. So it will take 100% of it's container's height.

---

## Upgrade instructions
- Rename any input values as needed (see breaking changes above)
- Remove the `height` input value 
- Import `SuperTabs.forRoot()` instead of `SuperTabs` in your app's main module.
